language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: cd68d7cf-1254-44eb-8af6-cf269781ded0
  app: tranquil-shore-80593
  on:
    repo: IamGrimUs/agglomeration
